[
  {
    "id": "I_kwDOMT5cIs6kn2c7",
    "number": 1544,
    "title": "callback throws - [\"⛔ TypeError: callback is not a function\"] - when action is called from the Twitter Client",
    "body": "**Describe the bug**\r\nWhen an action is initiated via the Twitter Client this error is thrown when the response of the action is sent back up the stack using callback(messageResponse). If the action is called using the Direct Client, no error occurs and the messageResponse is displayed in the client app.\r\n\r\n [\"⛔ TypeError: callback is not a function\"] \r\n\r\n**To Reproduce**\r\n\r\nThis error occurs when a client other than the Direct Client calls an action that sends a Content object through a HandlerCallback in the handler of an Action. This occurs when using plugin-image-generation to generating images as well. \r\n\r\nTo reproduce using the ImageGenerationPlugin:\r\n\r\nEnable the twitter client for your character along with an appropriate API key for image generation. Reply to a post of the Agent on twitter with \"Please generate an image of a cute cat!\" - it should trigger the GENERATE_IMAGE action. This will cause the TypeError to occur.\r\n\r\n**Expected behavior**\r\n\r\nI am unsure what the expected behavior should be. I would expect the callback to be able to take the Content object and pass it back to the client from which the action  was initiated from and some content text to be returned to the conversation that initiated the action.\r\n",
    "state": "OPEN",
    "createdAt": "2024-12-28T20:18:10Z",
    "updatedAt": "2024-12-28T20:20:29Z",
    "author": {
      "login": "Chunt0",
      "avatarUrl": "https://avatars.githubusercontent.com/u/87916117?u=f427255230f40af4131d7e90319e0db7350c0c79&v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": [
      {
        "id": "IC_kwDOMT5cIs6Y2hDJ",
        "author": "github-actions",
        "body": "Hello @Chunt0! Welcome to the ai16z community. Thank you for opening your first issue; we appreciate your contribution. You are now a ai16z contributor!"
      },
      {
        "id": "IC_kwDOMT5cIs6Y2hIA",
        "author": "monilpat",
        "body": "Thanks for sharing - This is due to the handler using the callback without\r\nchecking if it is nonnull as the callback param on the handler function is\r\nnullable\r\n\r\nOn Sat, Dec 28, 2024 at 12:18 PM Chunt0 ***@***.***> wrote:\r\n\r\n> *Describe the bug*\r\n> When an action is initiated via the Twitter Client this error is thrown\r\n> when the response of the action is sent back up the stack using\r\n> callback(messageResponse). If the action is called using the Direct Client,\r\n> no error occurs and the messageResponse is displayed in the client app.\r\n>\r\n> [\"⛔ TypeError: callback is not a function\"]\r\n>\r\n> *To Reproduce*\r\n>\r\n> This error occurs when a client other than the Direct Client calls an\r\n> action that sends a Content object through a HandlerCallback in the handler\r\n> of an Action. This occurs when using plugin-image-generation to generating\r\n> images as well.\r\n>\r\n> To reproduce using the ImageGenerationPlugin:\r\n>\r\n> Enable the twitter client for your character along with an appropriate API\r\n> key for image generation. Reply to a post of the Agent on twitter with\r\n> \"Please generate an image of a cute cat!\" - it should trigger the\r\n> GENERATE_IMAGE action. This will cause the TypeError to occur.\r\n>\r\n> *Expected behavior*\r\n>\r\n> I am unsure what the expected behavior should be. I would expect the\r\n> callback to be able to take the Content object and pass it back to the\r\n> client from which the action was initiated from and some content text to be\r\n> returned to the conversation that initiated the action.\r\n>\r\n> —\r\n> Reply to this email directly, view it on GitHub\r\n> <https://github.com/elizaOS/eliza/issues/1544>, or unsubscribe\r\n> <https://github.com/notifications/unsubscribe-auth/ADS6ROO24ZIK4DFWIVA2XVT2H4BRTAVCNFSM6AAAAABUKC6Q5CVHI2DSMVQWIX3LMV43ASLTON2WKOZSG43DCOJRGAYDONI>\r\n> .\r\n> You are receiving this because you are subscribed to this thread.Message\r\n> ID: ***@***.***>\r\n>\r\n"
      }
    ]
  },
  {
    "id": "I_kwDOMT5cIs6knwtr",
    "number": 1543,
    "title": "Unable to load sqlite-vec extensions in docker environment",
    "body": "**Describe the bug**\r\n\r\nUpon building the docker container and running locally, I am unable to start my agent. The agent works when I build in my local terminal.\r\n\r\nWhen I run the docker container, I receive the issue in the provided screenshot.\r\n\r\nI mainly interact with my agent via the Discord client. When I run locally, it responds to my messages and I can see the logs in terminal. When I run via docker, this does not occur.\r\n\r\n\r\n**To Reproduce**\r\n\r\n1. Run `docker build -t latest .`\r\n2. Run `docker run latest`\r\n\r\n\r\n**Expected behavior**\r\n\r\nI should be able to interact with my agent via Discord and see the appropriate logs in my terminal.\r\n\r\n**Screenshots**\r\n\r\n<!-- If applicable, add screenshots to help explain your problem. -->\r\n\r\n<img width=\"937\" alt=\"CleanShot 2024-12-28 at 14 38 51@2x\" src=\"https://github.com/user-attachments/assets/2779a416-5969-4b76-a9d7-c68ece191f01\" />\r\n\r\n**Additional context**\r\n\r\n<!-- Add any other context about the problem here. -->\r\n",
    "state": "OPEN",
    "createdAt": "2024-12-28T19:43:59Z",
    "updatedAt": "2024-12-28T20:04:26Z",
    "author": {
      "login": "iankm",
      "avatarUrl": "https://avatars.githubusercontent.com/u/10765530?u=10ced71da5b3364558289a76982aa52e67fffbc5&v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": [
      {
        "id": "IC_kwDOMT5cIs6Y2eNj",
        "author": "github-actions",
        "body": "Hello @iankm! Welcome to the ai16z community. Thank you for opening your first issue; we appreciate your contribution. You are now a ai16z contributor!"
      },
      {
        "id": "IC_kwDOMT5cIs6Y2gZX",
        "author": "IntrinsiCrypto",
        "body": "Can reproduce the issue, seems this is because the package doesn't have a `linux-arm64` target: https://github.com/asg017/sqlite-vec/issues/148"
      }
    ]
  },
  {
    "id": "I_kwDOMT5cIs6kmu3a",
    "number": 1523,
    "title": "Swap & Bridge action issue ",
    "body": "**Bug Report**\r\n\r\n#### **Describe the Bug**\r\n\r\nIn the `runtime.ts` file located at **packages\\core\\src\\runtime.ts**, the `processActions` function returns an empty `options` object during the execution of the EVM plugin of `bridgeAction` and `SwapAction` handlers, as the empty object does not contain the required information, leading to the failure of both the bridge and swap processes.\r\n\r\n---\r\n\r\n#### **To Reproduce**\r\n1. clone eliza main branch\r\n2. define WALLET_PUBLIC_KEY & WALLET_PRIVATE_KEY in `.env`\r\n3. Write prompt to swap 1 eth with 1 bsc or any chain swap or bridge \r\n4. After giving required details it will never execute your prompt it get an error cannot define toAddress and all details because its not composing actions\r\n---\r\n\r\n#### **Screenshots**\r\n\r\n1. **Process Action**\r\n     path: `packages\\core\\src\\runtime.ts`\r\n     ![image](https://github.com/user-attachments/assets/434e038d-8ecc-457a-889b-108fd2836283)\r\n     returns empty object as `Option`\r\n   \r\n2. **Bridge Action handler**\r\n      path: `packages\\plugin-evm\\src\\actions\\bridge.ts`\r\n      ![image](https://github.com/user-attachments/assets/f0c41650-7e9e-4558-8b0c-974d73d781e7)\r\n      transferring details of empty object details in bridge action\r\n",
    "state": "CLOSED",
    "createdAt": "2024-12-28T08:00:34Z",
    "updatedAt": "2024-12-28T08:05:29Z",
    "author": {
      "login": "ShahSujal",
      "avatarUrl": "https://avatars.githubusercontent.com/u/115413904?u=3564c8caccdf30992e9cc25876aab04daaac2856&v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": [
      {
        "id": "IC_kwDOMT5cIs6Y147G",
        "author": "ShahSujal",
        "body": "Fixed this issue with composing action with the required template\r\n\r\n**Bridge action**\r\n![image](https://github.com/user-attachments/assets/b52ffcbc-9187-4d79-9ceb-76da2bf1637a)\r\n\r\n**Swap action**\r\n![image](https://github.com/user-attachments/assets/da7b6c58-7e87-4470-be2e-6d4dd9e95dbd)\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
      }
    ]
  },
  {
    "id": "I_kwDOMT5cIs6kl2l8",
    "number": 1510,
    "title": "add fuel plugin",
    "body": "fuel is the fastest ethereum rollup with 600+ tps, also one of the cheapest. \r\n\r\nhttps://fuel.network",
    "state": "CLOSED",
    "createdAt": "2024-12-28T01:31:51Z",
    "updatedAt": "2024-12-28T02:12:28Z",
    "author": {
      "login": "Dhaiwat10",
      "avatarUrl": "https://avatars.githubusercontent.com/u/39617427?u=f285cc25c6d7a01ca00b676cf4869a1e29b62bca&v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qYA",
        "name": "enhancement",
        "color": "a2eeef",
        "description": "New feature or request"
      }
    ],
    "comments": [
      {
        "id": "IC_kwDOMT5cIs6Y1YdP",
        "author": "Dhaiwat10",
        "body": "fuel unfortuantely cannot make use of the existing evm plugin because fuel has its own virtual machine - the fuel virtual machine."
      },
      {
        "id": "IC_kwDOMT5cIs6Y1bFp",
        "author": "shakkernerd",
        "body": "Implemented in #1512 "
      }
    ]
  },
  {
    "id": "I_kwDOMT5cIs6klzF0",
    "number": 1506,
    "title": "Corrupt model `cache`",
    "body": "**Describe the bug**\r\n\r\nIf the process exits while the embedding model is being downloaded/extracted, the cache may be left in a corrupted state leading to warnings/errors such as the following:\r\n\r\n```\r\n⚠ Local embedding not supported in browser, falling back to remote embedding\r\n\r\n\"error\": {\r\n          \"message\": \"The model `BGE-small-en-v1.5` does not exist or you do not have access to it.\",\r\n          \"type\": \"invalid_request_error\",\r\n          \"param\": null,\r\n          \"code\": \"model_not_found\"\r\n      }\r\n```\r\n\r\nThe warning above is logged because of an error thrown from `FlagEmbedding.init(...)` in `embedding.ts` (this error is not logged in the console without some code changes):\r\n```\r\nError: Tokenizer file not found at /home/ubuntu/eliza/cache/fast-bge-small-en-v1.5/tokenizer.json\r\n    at FlagEmbedding.loadTokenizer (/home/ubuntu/eliza/node_modules/fastembed/lib/cjs/fastembed.js:139:19)\r\n    at FlagEmbedding.<anonymous> (/home/ubuntu/eliza/node_modules/fastembed/lib/cjs/fastembed.js:124:36)\r\n    at Generator.next (<anonymous>)\r\n    at fulfilled (/home/ubuntu/eliza/node_modules/fastembed/lib/cjs/fastembed.js:28:58)\r\n```\r\n\r\n_Without manually clearing the `cache` folder in which the embedding models are stored, the error will always occur._\r\n\r\n\r\n**To Reproduce**\r\n\r\nI'm not exactly sure how to consistently reproduce the corrupted cache with \"normal\" operation but you can do the following:\r\n1. Delete `cache/fast-bge-small-en-v1.5/tokenizer.json`\r\n2. Start an agent using local embeddings\r\n\r\n**Expected behavior**\r\n\r\n`pnpm clean` should resolve any cache related issues.\r\n\r\n**Screenshots**\r\n\r\n<!-- If applicable, add screenshots to help explain your problem. -->\r\n\r\n**Additional context**\r\n\r\n<!-- Add any other context about the problem here. -->\r\n",
    "state": "CLOSED",
    "createdAt": "2024-12-28T00:39:04Z",
    "updatedAt": "2024-12-28T03:16:11Z",
    "author": {
      "login": "timolegros",
      "avatarUrl": "https://avatars.githubusercontent.com/u/62490329?v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": []
  }
]
